name: zyromate_hr_task
description: Zyromate HR task using MVVM + Provider + API integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  intl: ^0.19.0
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
